# Nerine DB
DROP DATABASE IF EXISTS nerine_db;
CREATE DATABASE nerine_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE Persons(
    ID INT NOT NULL AUTO_INCREMENT,
    Name NVARCHAR(2048) NOT NULL,
    PRIMARY KEY ( ID )
);
CREATE TABLE Keywords(
    ID INT NOT NULL AUTO_INCREMENT,
    Name NVARCHAR(2048) NOT NULL,
    PersonID INT NOT NULL,
    PRIMARY KEY ( ID ),
    FOREIGN KEY ( PersonID ) REFERENCES Persons(ID)
);
CREATE TABLE Sites(
    ID INT NOT NULL AUTO_INCREMENT,
    Name NVARCHAR(256) NOT NULL,
    PRIMARY KEY ( ID )
);
CREATE TABLE Pages(
    ID INT NOT NULL AUTO_INCREMENT,
    Url NVARCHAR(2048) NOT NULL,
    SiteID INT NOT NULL,
    FoundDateTime DATETIME,
    LastScanDate DATETIME,
    PRIMARY KEY ( ID ),
    FOREIGN KEY ( SiteID ) REFERENCES Sites(ID)
);
CREATE TABLE PersonPageRank(
    PersonID INT NOT NULL,
    PageID INT NOT NULL,
    Rank INT DEFAULT 0,
    FOREIGN KEY ( PersonID ) REFERENCES Persons(ID),
    FOREIGN KEY ( PageID ) REFERENCES Pages(ID)
);