# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=2048)),
                ('LastScanDate', models.DateTimeField(auto_now=True)),
                ('FoundDateTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='PersonPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.PositiveIntegerField()),
                ('PageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='base.Page')),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='base.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='SiteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Site'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_words', to='base.Person'),
        ),
    ]
