# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=2048)),
                ('LastScanDate', models.DateTimeField(auto_now=True)),
                ('FoundDateTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2048)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonPageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.PositiveIntegerField()),
                ('PageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='root_api.Page')),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='root_api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='SiteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_api.Site'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_words', to='root_api.Person'),
        ),
    ]
