# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpagerank',
            name='pageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='userAPI.Pages'),
        ),
        migrations.AlterField(
            model_name='personpagerank',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='userAPI.Persons'),
        ),
    ]
